from typing import Protocol

from src.apps.users.domain.models import UserTrafficDailyInfo, UserTrafficSnapshotInfo


class UserTrafficView(Protocol):
    async def get_last_snapshot(self, user_uuid: str) -> UserTrafficSnapshotInfo | None: ...
    async def get_top_traffic(self, days: int, limit: int) -> list[UserTrafficDailyInfo]: ...
    async def get_top_traffic_today(self, limit: int) -> list[UserTrafficDailyInfo]: ...
    async def get_today_unalerted(self) -> list[UserTrafficDailyInfo]: ...
    async def get_avg_daily_7d(self, user_uuid: str) -> float: ...
    async def get_user_traffic_by_days(self, username: str, days: int) -> list[UserTrafficDailyInfo]: ...
