from datetime import datetime
from typing import Protocol


class AntifraudGateway(Protocol):
    async def mark_notified(self, remnawave_id: int, notified_at: datetime) -> None: ...
    async def mark_soft_notified(self, remnawave_id: int, notified_at: datetime) -> None: ...
    async def increment_violation_count(
        self, remnawave_id: int, now: datetime, window_seconds: int
    ) -> int: ...
    async def reset_violation_count(self, remnawave_id: int) -> None: ...
