"""add user traffic tables

Revision ID: 21e6386bc801
Revises: 62e470a0b397
Create Date: 2026-05-15 11:02:54.423051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21e6386bc801'
down_revision: Union[str, None] = '62e470a0b397'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_traffic_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_uuid', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('bytes_consumed', sa.BigInteger(), nullable=False),
    sa.Column('anomaly_alerted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_uuid', 'date', name='uq_user_traffic_daily')
    )
    op.create_index(op.f('ix_user_traffic_daily_date'), 'user_traffic_daily', ['date'], unique=False)
    op.create_index(op.f('ix_user_traffic_daily_user_uuid'), 'user_traffic_daily', ['user_uuid'], unique=False)
    op.create_table('user_traffic_last_snapshot',
    sa.Column('user_uuid', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('used_bytes', sa.BigInteger(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_traffic_last_snapshot')
    op.drop_index(op.f('ix_user_traffic_daily_user_uuid'), table_name='user_traffic_daily')
    op.drop_index(op.f('ix_user_traffic_daily_date'), table_name='user_traffic_daily')
    op.drop_table('user_traffic_daily')
    # ### end Alembic commands ###
