"""initial schema

Revision ID: 62e470a0b397
Revises: 
Create Date: 2026-05-14 14:38:09.223842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62e470a0b397'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('node_uuid', sa.String(length=255), nullable=False),
    sa.Column('node_name', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status_message', sa.String(length=1024), nullable=False),
    sa.Column('restart_attempts', sa.Integer(), nullable=False),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('downtime_seconds', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_node_uuid'), 'incidents', ['node_uuid'], unique=False)
    op.create_table('muted_nodes',
    sa.Column('node_uuid', sa.String(length=255), nullable=False),
    sa.Column('muted_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('muted_by_telegram_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('node_uuid')
    )
    op.create_table('node_stats_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('node_uuid', sa.String(length=255), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('users_online', sa.Integer(), nullable=False),
    sa.Column('traffic_used_bytes', sa.BigInteger(), nullable=False),
    sa.Column('xray_uptime', sa.Integer(), nullable=False),
    sa.Column('is_connected', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_stats_snapshots_captured_at'), 'node_stats_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_node_stats_snapshots_node_uuid'), 'node_stats_snapshots', ['node_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_node_stats_snapshots_node_uuid'), table_name='node_stats_snapshots')
    op.drop_index(op.f('ix_node_stats_snapshots_captured_at'), table_name='node_stats_snapshots')
    op.drop_table('node_stats_snapshots')
    op.drop_table('muted_nodes')
    op.drop_index(op.f('ix_incidents_node_uuid'), table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
