"""add antifraud notified users table

Revision ID: 8e2f87763af0
Revises: 21e6386bc801
Create Date: 2026-08-18 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e2f87763af0'
down_revision: Union[str, None] = '21e6386bc801'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('antifraud_notified_users',
    sa.Column('remnawave_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('remnawave_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('antifraud_notified_users')
    # ### end Alembic commands ###
